name: CI Pipeline

on:
  push


jobs:

  test:
    name: Test PR or Push to DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        run: |
          docker build . -t pyverilator

      - name: Run Tests
        run: |
          docker run --rm pyverilator pytest -n auto --verbose
